### ISSUE TITLE
LSTM Classification for Document Sentiment Task

### ISSUE THREAD

**Issue by Aditrhn** [IndoNLP/indonlu#15] opened 2020-11-27 17:14 UTC
Hi! Indobenchmark team.
I've been wondering, could I use LSTM for document sentiment task instead of logistic regression? I'm working on my thesis about document sentiment classification using BERT and LSTM. I'm pretty new to the topic and already tried the example code from finetune smsa, but I'm having a hard time on changing the code to use LSTM instead of logistic regression. It would be really helpful if you guys give me a hint about what should I use and what should I change from the example code. Thanks in advance 😄

**Comment by gentaiscool** [comment] 2020-11-27 18:39
Hi, @Aditrhn thank you for the question. I want to clarify that we are not using logistic regression in our model. Nevertheless, you can add LSTM on top of the BERT model. e.g., for word classification, you need to create a new class similar to BertForWordClassification in https://github.com/indobenchmark/indonlu/blob/master/modules/word_classification.py/. Since you are working on the Sequence Classification, you can directly copy the implementation of BertForSequenceClassification from https://huggingface.co/transformers/_modules/transformers/modeling_bert.html#BertForSequenceClassification, and replace self.classifier with LSTM and an additional nn.Linear classifier. You also need to modify the forward function.

Hopefully, the answer helps.

**Comment by Aditrhn** [comment] 2020-11-29 12:46
Thank you for the answer @gentaiscool . Ahh so you guys not using logistic regression, what do you use then?
Also what I need to do is create a new class on top of BERT model, and I can copy the implementation from the link above right?
So I tried to do what you told me to, firstly I copy the implementation from https://huggingface.co/transformers/_modules/transformers/modeling_bert.html#BertForSequenceClassification and then I put it on top of my bert model, in example I put it on top of Load Model Markdown in https://github.com/indobenchmark/indonlu/blob/master/examples/finetune_smsa.ipynb. After that I replace self.classifier with LSTM so it look like this :
![image](https://user-images.githubusercontent.com/33977433/100542292-85145300-327b-11eb-9fd7-7b00f8f999e1.png)


Am I doing it right? And also I'm still confused about what should I change from nn.classifier and forward function. In case you need to see my code, you can look at it here [https://colab.research.google.com/drive/1XUgSwi_0UaiSZaho7SmpYgNGoMq62Duo?usp=sharing](url). Thanks for the help!

**Comment by SamuelCahyawijaya** [comment] 2020-11-29 15:02
Hi @Aditrhn,

First of all we are using **PyTorch** framework here instead of **Keras**, I am not sure combining both frameworks into one codebase is a good idea.

Secondly, if what you are expecting is to use **BERT with LSTM head** instead of **BERT with Linear head**, then your modification is almost correct. Basically what you need to do is to add the LSTM and linear layer (in a **PyTorch** way), and update the forward function on **BertForSequenceClassificationLSTM** class that you have made.

As long as you keep the return of the forward function consistent with our predefined class, then the whole script should be able to work just fine.

You can define the LSTM and the Linear (Dense) on top of LSTM as follow:
```
       # Assuming that you are expecting 1-layer LSTM with 128 hidden size and non-biderectional 
       # with bert-base setting as you BERT model
       self.lstm = nn.LSTM(input_size=768, hidden_size=128, num_layers=2)
       self.linear = nn.Linear(128, config.num_labels)
```

And in forward function what you need to do are as follow:
1. Take sequence output from BERT, something like:
```
        outputs = self.bert(...)
        sequence_output = outputs[0] # Index 0 is sequence output, index 1 is pooler output
```
2. Then you need to perform padding for LSTM with `pack_padded_sequence` function (https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html)
3. After that you can feed the resulting tensor into LSTM, something similar as follow:
```
outputs, (h_n, c_n) = self.lstm(padded_inputs)
```
4. And lastly you can take the last layer of hidden state and feed it into the linear head defined above
```
linear_input = h_n.view(num_layers, num_directions, batch, hidden_size)[-1,0,:,:]
output = self.linear(linear_input)
```

For more detail on how to use LSTM, you can check the official documentation and tutorial:
- https://pytorch.org/docs/stable/generated/torch.nn.LSTM.html
- https://pytorch.org/docs/stable/generated/torch.nn.utils.rnn.pack_padded_sequence.html
- https://pytorch.org/tutorials/beginner/nlp/sequence_models_tutorial.html

I hope this answer can guide you to solve your issue.

**Comment by Aditrhn** [comment] 2020-11-30 15:37
Thank you @SamuelCahyawijaya  for providing instructions on how to use LSTM. 

So I've changed my framework to use PyTorch and I've also read some documentation and tutorials on how to use pack_padded_sequence. From the steps that you instructed and some documentation and tutorials that I read, I finally made the code like this :

```python
class BertForSequenceClassificationLSTM(BertPreTrainedModel):
    def __init__(self, config):
        super().__init__(config)
        self.num_labels = config.num_labels

        self.bert = BertModel(config)
        self.dropout = nn.Dropout(config.hidden_dropout_prob)
        self.lstm = nn.LSTM(input_size=768, hidden_size=128, num_layers=2)
        self.linear = nn.Linear(128, config.num_labels)

        self.init_weights()

    def forward(
        self,
        input_ids=None,
        attention_mask=None,
        token_type_ids=None,
        position_ids=None,
        head_mask=None,
        inputs_embeds=None,
        labels=None,
        output_attentions=None,
        output_hidden_states=None,
        return_dict=None,
    ):
        r"""
        labels (:obj:`torch.LongTensor` of shape :obj:`(batch_size,)`, `optional`):
            Labels for computing the sequence classification/regression loss. Indices should be in :obj:`[0, ...,
            config.num_labels - 1]`. If :obj:`config.num_labels == 1` a regression loss is computed (Mean-Square loss),
            If :obj:`config.num_labels > 1` a classification loss is computed (Cross-Entropy).
        """
        return_dict = return_dict if return_dict is not None else self.config.use_return_dict

        outputs = self.bert(
            input_ids,
            attention_mask=attention_mask,
            token_type_ids=token_type_ids,
            position_ids=position_ids,
            head_mask=head_mask,
            inputs_embeds=inputs_embeds,
            output_attentions=output_attentions,
            output_hidden_states=output_hidden_states,
            return_dict=return_dict,
        )

        sequence_output = outputs[0]

        padded_inputs = pack_padded_sequence(sequence_output, lengths, batch_first=False)
        outputs, (h_n, c_n) = self.lstm(padded_inputs)

        linear_input = h_n.view(num_layers, num_directions, batch, hidden_size)[-1,0,:,:]
        output = self.linear(linear_input)

        sequence_output = self.dropout(sequence_output)
        logits = self.LSTM(sequence_output)

        loss = None
        if labels is not None:
            if self.num_labels == 1:
                #  We are doing regression
                loss_fct = MSELoss()
                loss = loss_fct(logits.view(-1), labels.view(-1))
            else:
                loss_fct = CrossEntropyLoss()
                loss = loss_fct(logits.view(-1, self.num_labels), labels.view(-1))

        if not return_dict:
            output = (logits,) + outputs[2:]
            return ((loss,) + output) if loss is not None else output

        return SequenceClassifierOutput(
            loss=loss,
            logits=logits,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
        )
```
I'm still confused at `padded_inputs = pack_padded_sequence(sequence_output, lengths, batch_first=False)`, what should I use to change the `lengths` parameter? 

I have tried to change it based on what I read from BertModel class in https://huggingface.co/transformers/_modules/transformers/modeling_bert.html#BertModel and BertEmbeddings class in https://huggingface.co/transformers/_modules/transformers/modeling_bert.html#BertEmbeddings but an error still occurs when trying the model in the example sentence. 

I haven't checked the rest of the code for errors because the length parameter still has an error.

**Comment by SamuelCahyawijaya** [comment] 2020-11-30 15:56
Ah yeah, I think you are on the right track. To find the length, I believe the easiest way is to take it from the `attention_mask`, it should be just sum of the `attention_mask` for each element in each row, something like the following:
```
# numpy
length_batch = attention_mask.sum(axis=-1)

# PyTorch
length_batch = attention_mask.sum(dim=-1)
```

And I think these two lines are not necessary
```
sequence_output = self.dropout(sequence_output)
logits = self.LSTM(sequence_output)
```

**Comment by Aditrhn** [comment] 2020-12-01 02:02
I've added the code to sum `attention_mask` so it look like this :
```python
sequence_output = outputs[0]
length_batch = attention_mask.sum(axis=-1)

padded_inputs = pack_padded_sequence(sequence_output, sum, batch_first=False)
```

And I tried to test the model on sample sentences using this code :
```python
text = 'Hotel tidak bisa tanggung jawab males banget pokoknya.'
subwords = tokenizer.encode(text)
subwords = torch.LongTensor(subwords).view(1, -1).to(model.device)

logits = model(subwords)[0]
label = torch.topk(logits, k=1, dim=-1)[1].squeeze().item()

print(f'Text: {text} | Label : {i2w[label]} ({F.softmax(logits, dim=-1).squeeze()[label] * 100:.3f}%)')
```

But the code return the following errors :
```python
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-18-bb506ec279ee> in <module>()
      3 subwords = torch.LongTensor(subwords).view(1, -1).to(model.device)
      4 
----> 5 logits = model(subwords)[0]
      6 label = torch.topk(logits, k=1, dim=-1)[1].squeeze().item()
      7 

<ipython-input-5-61bd738b7375> in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict)
     45 
     46         sequence_output = outputs[0]
---> 47         length_batch = attention_mask.sum(axis=-1)
     48 
     49         padded_inputs = pack_padded_sequence(sequence_output, length_batch, batch_first=False)

AttributeError: 'NoneType' object has no attribute 'sum'
```
I also tried to change `length_batch` value to `np.sum(attention_mask, axis=-1)`, but it returns `TypeError: an integer is required (got type NoneType)`

**Comment by SamuelCahyawijaya** [comment] 2020-12-01 04:36
@Aditrhn : Ah yeah, obviously it won't work on that one, because you call the model without passing the attention mask 
```
logits = model(subwords)[0]
```
in this case, you can add if `attention_mask is None` then you use the sequence length of the input

**Comment by Aditrhn** [comment] 2020-12-03 15:02
> @Aditrhn : Ah yeah, obviously it won't work on that one, because you call the model without passing the attention mask
> 
> ```
> logits = model(subwords)[0]
> ```
> 
> in this case, you can add if `attention_mask is None` then you use the sequence length of the input

I'm not really sure what to change or what to add, but I tried to change some codes. I tried to put `attention_mask is None`, but not sure if I put it on the right place, it look like this :
```python
sequence_output = outputs[0]
if attention_mask is None:
  length_batch = len(sequence_output)
else:
  length_batch = attention_mask.sum(dim=-1)

padded_inputs = pack_padded_sequence(sequence_output, length_batch, batch_first=False)
```

I also changes the sample sentence code so it would pass the `attention_mask`, the code look like this :
```python
text = 'Pegawai ramah sekali kamarnya nyaman, makananya enak, request terpenuhi, rasanya tidak pengen pulang :( , recomended banget deh!'
subwords = tokenizer(text)
attention_mask = subwords["attention_mask"]
subwords = torch.LongTensor(subwords["input_ids"]).view(1, -1).to(model.device)

logits = model(subwords, attention_mask)[0]
label = torch.topk(logits, k=1, dim=-1)[1].squeeze().item()

print(f'Text: {text} | Label : {i2w[label]} ({F.softmax(logits, dim=-1).squeeze()[label] * 100:.3f}%)')
```
But it return this errors message :
```python
AttributeError                            Traceback (most recent call last)
<ipython-input-88-70386453224f> in <module>()
      4 subwords = torch.LongTensor(subwords["input_ids"]).view(1, -1).to(model.device)
      5 
----> 6 logits = model(subwords, attention_mask)[0]
      7 label = torch.topk(logits, k=1, dim=-1)[1].squeeze().item()
      8 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

<ipython-input-76-28a73dfc06a5> in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, labels, output_attentions, output_hidden_states, return_dict)
     41             output_attentions=output_attentions,
     42             output_hidden_states=output_hidden_states,
---> 43             return_dict=return_dict,
     44         )
     45 

/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py in _call_impl(self, *input, **kwargs)
    725             result = self._slow_forward(*input, **kwargs)
    726         else:
--> 727             result = self.forward(*input, **kwargs)
    728         for hook in itertools.chain(
    729                 _global_forward_hooks.values(),

/usr/local/lib/python3.6/dist-packages/transformers/models/bert/modeling_bert.py in forward(self, input_ids, attention_mask, token_type_ids, position_ids, head_mask, inputs_embeds, encoder_hidden_states, encoder_attention_mask, output_attentions, output_hidden_states, return_dict)
    820         # We can provide a self-attention mask of dimensions [batch_size, from_seq_length, to_seq_length]
    821         # ourselves in which case we just need to make it broadcastable to all heads.
--> 822         extended_attention_mask: torch.Tensor = self.get_extended_attention_mask(attention_mask, input_shape, device)
    823 
    824         # If a 2D or 3D attention mask is provided for the cross-attention

/usr/local/lib/python3.6/dist-packages/transformers/modeling_utils.py in get_extended_attention_mask(self, attention_mask, input_shape, device)
    228         # We can provide a self-attention mask of dimensions [batch_size, from_seq_length, to_seq_length]
    229         # ourselves in which case we just need to make it broadcastable to all heads.
--> 230         if attention_mask.dim() == 3:
    231             extended_attention_mask = attention_mask[:, None, :, :]
    232         elif attention_mask.dim() == 2:

AttributeError: 'list' object has no attribute 'dim'
```
When I change the `attention_mask = subwords["attention_mask"]` to `attention_mask = len(subwords["attention_mask"])`, the error change to `AttributeError: 'int' object has no attribute 'dim'`

**Comment by SamuelCahyawijaya** [comment] 2020-12-03 16:50
@Aditrhn : I think both ways are fine, but I think the first one would be simpler. On your code right now you have:
``` 
sequence_output = outputs[0]
if attention_mask is None:
  length_batch = len(sequence_output)
else:
  length_batch = attention_mask.sum(dim=-1)

padded_inputs = pack_padded_sequence(sequence_output, length_batch, batch_first=False)
```
the `sequence_output` shape should be `batch_size` * `sequence_length` * `model_dimension`, in this case you may need to specify:
```
length_batch = torch.LongTensor([sequence_output.shape[1]])
```

Remember that this is a hacky way to handle the single data inference with `batch_size` = 1, I think it should be ok in most of the case.

I make a minimal example of using `pack_padded_sequence` for your case. `x` could be either the `sequence_output` variable or the input sequence to the model.
<img width="898" alt="Screenshot 2020-12-04 at 12 47 30 AM" src="https://user-images.githubusercontent.com/2826602/101060539-7d7de280-35ca-11eb-891c-1b5819efd5fc.png">

**Comment by Aditrhn** [comment] 2020-12-04 16:44
Alright, I somehow managed to solve the problem by using your example code and modified it a little bit so it look like this
```python
sequence_output = outputs[0]
if attention_mask is None:
  length_batch = torch.LongTensor([sequence_output.shape[0]]).repeat(sequence_output.shape[1])
else:
  length_batch = attention_mask.sum(dim=-1)
```
And it works well until it execute this line of code
```python
linear_input = h_n.view(num_layers, num_directions, batch, hidden_size)[-1,0,:,:]
output = self.linear(linear_input)
```
It returns an error that say `num_layers`, `num_directions`, `batch`, and `hidden_size` is  not defined. I thought it was already defined in `self.lstm = nn.LSTM(input_size=768, hidden_size=128, num_layers=2)`. Nevertheless I define the variables above the `linear_input` so it look like this :
```python
num_layers = 2
num_directions = 1
linear_input = h_n.view(num_layers, num_directions, batch, hidden_size)[-1,0,:,:]
output = self.linear(linear_input)
```
But I don't know what batch variable should be filled with, and also I assumed I should use 128 from `self.lstm = nn.LSTM(input_size=768, hidden_size=128, num_layers=2)` as the value of `hidden_size` right?

**Comment by SamuelCahyawijaya** [comment] 2020-12-04 17:24
@Aditrhn : if `batch` variable refers to batch size, then you can get it from `sequence_output.shape[0]` and I believe this one is also incorrect
```
length_batch = torch.LongTensor([sequence_output.shape[0]]).repeat(sequence_output.shape[1])
```
I believe this one should be
```
length_batch = torch.LongTensor([sequence_output.shape[1]]).repeat(sequence_output.shape[0])
```
because what you want is to make a pad with a length of input length and you want to apply it to each data in the batch.

You should remember that the dimensionality of input and output from the transformer model is  `batch_size` x `seq_length` x  `model_dim`. This is the convention applies for all huggingface transformer models. While in the PyTorch LSTM, the input should be `seq_len`, `batch`, `input_dim` so you might want to permute the `sequence_output` tensor  to match what is required for LSTM.

>  I assumed I should use 128 from self.lstm = nn.LSTM(input_size=768, hidden_size=128, num_layers=2) as the value of hidden_size right?

I think you need to get a better understanding of the commonly used terms in modeling and all the layers in sequence modeling, especially for LSTM and transformer. Because this is not a question that is suitable to be asked here, it should be something that you should have known even before you go deeper to do research in deep learning.

**Comment by gentaiscool** [comment] 2020-12-16 09:24
I will close this issue. Please re-open this issue if you want to follow-up. Thanks

**Closed as completed by gentaiscool** 2020-12-16 09:24 UTC
Labels: question
